### ISSUE TITLE
Make it possible to change intervals

### ISSUE THREAD

**Issue by shellstrom** [JosiahLeas/josiahleas.github.io#16]
Currently the interval is fixed at 1H, which is fine as a start, but it should be possible to modify that.

* For all charts at once?
* One chart at a time?
* Startup?

**Comment by qwerty1891** [comment]
this should be solved by this commit:
https://github.com/JosiahLeas/josiahleas.github.io/commit/67f3a55713af4b2e7a2d0cc7e5180c81ad4e10c1

**Comment by shellstrom** [comment]
If so, provide a user test case so it can be verified so we can close this issue.

**Comment by restinpieces** [comment]
Maybe I'm wrong, but this should be easy.

You load the charts from e.g. 
https://s.tradingview.com/widgetembed/?symbol=BITfinex:btcUSD&interval=60&hidesidetoolbar=0&symboledit=0&saveimage=1&toolbarbg=rgb(227, 232, 248)&studies=[]&hideideas=1&theme=Light&style=1&timezone=Etc/UTC&studies_overrides={}&overrides={}&enabled_features=[]&disabled_features=[]&locale=en&utm_source=www.multicoincharts.com&utm_medium=widget&utm_campaign=chart&utm_term=BITfinex:btcUSD


interval=60 is where the time is coded. couldn't you add an interval var to your url that changes all the chart intervals?

like:
https://www.multicoincharts.com/testdrive.html?chart=BITfinex:btcUSD&interval=XYZ
corresponds to 

https://s.tradingview.com/widgetembed/?symbol=BITfinex:btcUSD&interval=XYZ&.....
on all the open charts?

**Comment by qwerty1891** [comment]
@restinpieces: I believe that is already added under "Additional charts parameters:" when you click "Add Chart" button. It's named "Default Interval"

**Comment by restinpieces** [comment]
I didn't know this option existed, because I rarely use it. I usually enter via custom bookmark. 

This is a great feature, I'd still like to set the interval via url though.

**Comment by P-Medicado** [comment]
@restinpieces this feature is being tested in one of our pull requests, should see it in url params soon!
