### ISSUE TITLE
Adding/Removing charts

### ISSUE THREAD

**Issue by shellstrom** [JosiahLeas/josiahleas.github.io#18]
The way of adding and removing charts is cumbersome. It would benefit from a UI where this can be done more intuitively.

**Comment by qwerty1891** [comment]
this should be solved by this commit:
https://github.com/JosiahLeas/josiahleas.github.io/commit/67f3a55713af4b2e7a2d0cc7e5180c81ad4e10c1

**Comment by xworkscom** [comment]
Why did you change original way of changing currency in chart? In new UI I can't have same coin on one screen. I need to see same coin in different time frames. New updates by qwerty are contra productive, especially buttons that are covering price.
Just go back to initial version, that was perfect, there was nothing else to make it better, only worse.

**Comment by JosiahLeas** [comment]
UI is being worked on since a lot of people seem to not like the new update. I will more than likely just revert it to essentially the same as it was before.
