### ISSUE TITLE
Investigate investing.com's use of charts

### ISSUE THREAD

**Issue by shellstrom** [JosiahLeas/josiahleas.github.io#22]
https://www.investing.com/charts/cryptocurrency-charts is using a widget or something or other, that seem to be running the latest TradingView widget(?).

If that's something we could utilise (they have a 4x4 grid built in, synced cursor, etc), it could be a potential added benefit to the service we provide.

**Comment by qwerty1891** [comment]
I can't seem to find the 4x4 with the synced cursor
Any other way I can see it?

**Comment by P-Medicado** [comment]
Looked into synchronized cursors, couldn't find any info tonight but it is a goal. may have to use js canvas except I don't think we have access to their iframe js canvas
