### ISSUE TITLE
Replace all style-tags with CSS classes

### ISSUE THREAD

**Issue by shellstrom** [JosiahLeas/josiahleas.github.io#27]
https://github.com/JosiahLeas/josiahleas.github.io/blob/2fb8fa601505e5dc026a40978b4c441e080ecf0c/main.html#L30

Style-tags are not going to be easily maintainable and should be replaced with classes and CSS equivalents

**Comment by JosiahLeas** [comment]
[nonissue] Thank you for your feedback - style vs class does not effect usability of [MCC](http://multicoincharts.com)
