### ISSUE TITLE
Merge "Single chart" and "Multi-Chart" configs

### ISSUE THREAD

**Issue by shellstrom** [JosiahLeas/josiahleas.github.io#28]
I can see no reason for having two separate configuration views.

* If there's only one chart, then let the settings reflect that
* If there are multiple views, then let the settings reflect that

The singe chart view is not adding anything unique that the multi config chart doesn't already take into account. All the functionality in the single chart config already exist in the multi chart one.

**Comment by P-Medicado** [comment]
You're right this was good to merge
