### ISSUE TITLE
Add new markets alert/notification/popup when added to exchanges

### ISSUE THREAD

**Issue by dhaern** [JosiahLeas/josiahleas.github.io#29]
Is it possible add a new markets notification/alert when they are added to exchanges?? It's good for not miss the first hours trading on new markets. It would be amazing for cryptocoins.

I didnt find this feature, only Coinigy have this one but it would be much better adding to your extension and maybe this code helps you: https://github.com/ekittell/bittrex_alert

Here do you have an example/idea from Coinigy

![](https://user-images.githubusercontent.com/7317522/33096596-72a75894-ceff-11e7-90c7-3565cf92884d.png)

Thanks.

**Comment by JosiahLeas** [comment]
I don't really think this is something that should be added to the site. I could maybe work on it as a side project though. Have it email or something when a new coin is listed. Thanks for the suggestion.
