### ISSUE TITLE
Spreading not addeding correctly 

### ISSUE THREAD

**Issue by Willstar44** [JosiahLeas/josiahleas.github.io#38]
when you add a spread like (XBTUSD-(BTCUSD+BTCUSD)/2)/((BTCUSD+BTCUSD)/2)*100

it removes the + and adds % 
(XBTUSD-(BTCUSD%20BTCUSD)/2)/((BTCUSD%20BTCUSD)/2)*100
ps. because we cant log in, you can only use spread on the daily charts 

also is there a way to add the compare to the bookmark like BTCUSD/ LTC USD  to the singles chart

**Comment by P-Medicado** [comment]
Where are you adding spread? In the URL? in the trading view box?
