### ISSUE TITLE
Scale down the Full screen and Remove button

### ISSUE THREAD

**Issue by arsenicks** [JosiahLeas/josiahleas.github.io#41]
It might be nice to scale down the Full screen and Remove button. It's impossible to see the current value when market are going down.

<img width="166" alt="screen shot 2018-01-30 at 8 13 38 pm" src="https://user-images.githubusercontent.com/22738397/35600150-76b5c402-05fa-11e8-9cd6-04fefdc13574.png">

Thanks for your work!

**Comment by JosiahLeas** [comment]
That's already a feature.

Simply select "Use Small Buttons" under the "Add Chart" menu.

**Comment by arsenicks** [comment]
Oh god, I feel dumb. I've never clicked on this button because I've never wanted to add annother chart. Don't you think Options or something like that would be better ? Or I might be the only Dumbass around ;)
