### ISSUE TITLE
Trading View CSV export, Import to MCC

### ISSUE THREAD

**Issue by jamesrogers93** [JosiahLeas/josiahleas.github.io#42]
Would it be possible to add multiple symbols at once using comma separated pairs?

This would be very useful as I would be able to paste an exported [watchlist.txt](https://github.com/JosiahLeas/josiahleas.github.io/files/1836751/watchlist.txt) from trading view directly into MCC.

I have experiemented with this by changing part of the inputPairs(element) function in index.js to: 

```javascript
        if (isEnter) {
            var chartTickers = element.value.toUpperCase().split(',');
            var chartTickersLen = chartTickers.length;

            for(var i = 0; i < chartTickersLen; i++) {
                chartTicker = chartTickers[i];
                listPairs = document.getElementById('listPairs');
                listPairs.options[listPairs.options.length] = new Option(chartTicker, chartTicker);
            }

            element.value = "";
            document.getElementById("pairsInput").focus();
}
```

This seems to work.

**Comment by P-Medicado** [comment]
We can implement a feature which converts a trading view csv into mcc proprietary url parameter format. Would this be sufficient for you? - also is this a feature many users would like?

**Comment by P-Medicado** [comment]
This feature can be a sub-page of MCC where a CSV is uploaded, then the MCC URL is generated, finally, is assigned to window.location

I'm sorry for not getting back to this earlier.
