### ISSUE TITLE
Add query param with Indicators and settings

### ISSUE THREAD

**Issue by vijay-r** [JosiahLeas/josiahleas.github.io#47]
Please add query param with Indicators and settings
?Indicators=DONCH,MACD&settings=[interval=1d],.......

**Comment by P-Medicado** [comment]
Hi, we've thought about how this addition would possibly interfere against settings or preferences already saved in a user's browser. 

What do you think? Should these URL attributes override the user's saved settings. 
If so, should it become the new settings saved.

There may be other options not yet considered, please let us know!

**Comment by zzaki8950** [comment]
hello 
what i need do for not get redirected in your website when i upload the project to my domain then i open my url then in 2 second he redirected to your website

**Comment by tcmac** [comment]
谢谢

**Comment by zzaki8950** [comment]
> > hello what i need do for not get redirected in your website when i upload the project to my domain then i open my url then in 2 second he redirected to your website
> 
> Unfortunately we are a closed source project now due to a few bad actors copying the code and monetizing on their own domain. I hope you understand.
> 
> It is still in active development so feel free to suggest features. I will add them as I have time.

So that not a free open source project ? how i can buy source code

**Comment by zzaki8950** [comment]
can contact you ? in whatsapp or skype

**Comment by zzaki8950** [comment]
Why you tell me i al scammer , not just you see issue not from me , then said me scammer , you should understand fist then said me what you want , i can find dev make me same of your website, but i not like that , i come to and ask you , so don’t think your are good men and the other is bad , why
