### ISSUE TITLE
Cannot Add Charts

### ISSUE THREAD

**Issue by milezzz** [JosiahLeas/josiahleas.github.io#49]
I git clone this and got some errors in console. Particularly cannot add charts due to this 403 error:

![image](https://user-images.githubusercontent.com/2200225/109265615-72eb7780-77cc-11eb-8a80-19461ad50c7a.png)

![image](https://user-images.githubusercontent.com/2200225/109266744-0f624980-77ce-11eb-92f6-40848bce5c19.png)

Confusingly The offending URL seems to load fine in a browser: https://symbol-search.tradingview.com/symbol_search/?text=&hl=1&exchange=BITMEX&lang=en&type=crypto&domain=production 

I changed my URL in CNAME and the other files but can't think what I could be missing. Anyone else been able to get this working?

**Comment by P-Medicado** [comment]
We know about this issue but haven't found a way to solve it yet.

The 403 Error is Forbidden Access coming from TradingView. We are trying to get access supported for the live version of our site but it only partially works. 

This isn't a bug in the multicoincharts codebase, to try to fix this problem, you need a web server which won't get rejected by TradingView

**Comment by milezzz** [comment]
>you need a web server which won't get rejected by TradingView

Well if that was the case all I should have to do is change my IP and it should work right? I did that (3 different IPs) and got the same 403 error. To further test this thesis I did a curl request on the command line and the data was returned properly.

I'm super confused what the issue is but being blocked by TV doesn't seem to be the culprit. Am I missing something? 

Also was hoping this thread could stay open because I can't be the only person facing this issue. I mean perhaps we can proxy around it or build a solution.

**Comment by milezzz** [comment]
>>you need a web server which won't get rejected by TradingView

Well if that was the case all I should have to do is change my IP and it should work right? I did that (3 different IPs) and got the same 403 error. To further test this thesis I did a curl request on the command line and the data was returned as expected.

```
curl -I https://symbol-search.tradingview.com/symbol_search/?text=&hl=1&exchange=COINBASE&lang=en&type=crypto&domain=production

HTTP/2 200 
server: nginx
date: Wed, 03 Mar 2021 22:53:06 GMT
content-type: application/json; charset=utf-8
content-length: 6165
access-control-allow-methods: GET
access-control-allow-headers: Content-Type
access-control-max-age: 86400
cache-control: public, max-age=120

[1] 17595
[2] 17596
[3] 17597
[4] 17598
[5] 17599
[2]   Done                    hl=1
[3]   Done                    exchange=COINBASE
[4]-  Done                    lang=en
```

I'm super confused what the issue is but being blocked by TV doesn't seem to be the culprit unless I'm missing something? I checked an older version of MCC and it appears to be working properly listing pairs, isn't the call made the same way in older versions?

**Comment by P-Medicado** [comment]
I'm sorry, even though I am responding to you on this GitHub account, I personally was not working on MCC on versions too long ago. We can reopen this issue until we figure out if this is a bug in our repo.

**Comment by milezzz** [comment]
I think I see how to fix this issue but the code in this file is unnecessarily obfuscated making it very difficult: https://github.com/JosiahLeas/josiahleas.github.io/blob/master/js/copypasta.min.js

Do you have a clean copy of this? If so I'd be willing to fix the problem.
